language: node_js
node_js:
  - "4.1"
  - "0.12"

before_script:
  mkdir -p build/misc;
  git clone --branch=master https://github.com/JBZoo/Misc.git build/misc;

script:
  - npm run test
  - npm run jshint
  - npm run jscs
